config/routes.rb
Plasa98::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount Ckeditor::Engine => '/ckeditor'

  root 'home#index'
  get 'category/:category/item/:item' => 'home#item', as: 'item'
  get 'category/:category' => 'home#category', as: 'category'
  get 'page/:page' => 'home#page', as: 'page'
  post 'process_buy/:item' => 'home#process_buy', as:'process_buy'
  get 'search' => 'home#search', as: 'search'
  post 'contact_us' => 'home#contact_us', as: 'contact_us'
  get 'banner' => 'home#banner', as: 'banner'
  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
         
  attr_accessible :email, :password, :password_confirmation
  
end

app/models/banner.rb
class Banner < ActiveRecord::Base
  PLACE = ['kanan','kiri']
  attr_accessible :image, :link_url, :place
  mount_uploader :image, ImageUploader
  
  scope :left, -> { where(place: 'kiri') }
  scope :right, -> { where(place: 'kanan') }
  
  def place_from
    self.place == 'kiri' ? 'kiri' : 'kanan'
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :items
  attr_accessible :name
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, :to => :data

  validates_presence_of :data
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, :mount_on => :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :name, :handphone, :email, :message
  validates :name, :handphone, :email, :message, presence: {message: 'tidak boleh kosong'}
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  belongs_to :item
  attr_accessible :item_id, :handphone, :address, :name
  validates :item_id, :handphone, :address, :name, presence: {message: 'tidak boleh kosong'}
end

app/models/image.rb
class Image < ActiveRecord::Base
  
  belongs_to :item
  attr_accessible :image, :item_id
  mount_uploader :image, ImageUploader
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :feedbacks
  belongs_to :category
  has_many :images
  attr_accessible :name, :amount, :rate, :description, :is_available, :category_id, :is_hot, :images_attributes, :is_favorite
  accepts_nested_attributes_for :images
  paginates_per 40
  
  validates :name, :amount, :rate, :description, :category, presence: {message: 'tidak boleh kosong'}
  validate :rating
  
  default_scope order('updated_at DESC')
  
  scope :hots, -> { where(is_hot: true).limit(5) }
  scope :favorites, -> { where(is_favorite: true).limit(5) }
  
  def image_seconds
    self.images.delete_if{|x| self.images.first.id == x.id } rescue []
  end
  
  def rating
    errors.add(:rate, "rating harus 1 sampai 5") if self.rate.to_i > 5
  end
  
  def mini_url
    self.images.first.image.url(:mini) rescue "/assets/image1.jpg"
  end
  
  def thumb_url
    self.images.first.image.url(:thumb) rescue ""
  end
  
  def large_url
    self.images.first.image.url(:large) rescue ""
  end
  
  def available?
    self.is_available?? 'Tersedia' : 'Tidak tersedia'
  end
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible  :content, :name
  
  def self.create_additional_page
    pages = ['galeri video','cek ongkos kirim','cek resi JNE']
    
    pages.each do |p|
      Page.create(name: p, content: "ini adalah halaman untuk #{p}")
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :all_case
  
  def index
    @items = Item.all
    @items = Kaminari.paginate_array(@items).page(params[:page]) if @items.class == Array
    @items = @items.page(params[:page])
  end
  
  def page
    slug = unslug(params[:page])
    @page = Page.find_by_name(slug)
    return ( not_found ) unless @page
  end
  
  def item
    slug = unslug(params[:item])
    cslug = unslug(params[:category])
    c = Category.find_by_name(cslug)
    return ( not_found ) unless c
    @item = Item.find_by_name_and_category_id(slug, c.id)
    return ( not_found ) unless @item
  end
  
  def category
    slug = unslug(params[:category])
    @category = Category.find_by_name(slug)
    return ( not_found ) unless @category
    @items = @category.items
    @items = Kaminari.paginate_array(@items).page(params[:page]) if @items.class == Array
    @items = @items.page(params[:page])
  end
  
  def process_buy
    item_id = params[:item_id]
    handphone = params[:telepon]
    address = params[:alamat]
    name = params[:name]
    f = Feedback.new(item_id: item_id, address: address, name: name, handphone: handphone)
    if f.save
      flash[:notice] = 'terima kasih, transaksi anda akan segera kami proses'
    else
      flash[:error] = 'transaksi tidak bisa kami proses, silahkan ulangi kembali'
    end
    redirect_to :back
  end
  
  def search
    @s = params[:filter_name]
    if @s.present?
      @items = Item.where('name LIKE ?',"%#{@s}%")
      return ( not_found ) unless @items
      @items = Kaminari.paginate_array(@items).page(params[:page]) if @items.class == Array
      @items = @items.page(params[:page])
    else
      c = Category.find_by_id(params[:categories]).name.split(' ').join('-') rescue '-'
      redirect_to category_path(c)
    end
  end
  
  def contact_us
    f = Contact.new(params[:contact_us])
    if f.save
      flash[:notice] = 'kirim pesan berhasil'
    else
      flash[:error] = 'kirim pesan ke admin gagal, harap isi semua field dengan benar'
    end
    redirect_to :back
  end
  
  def banner
    @banners_left = Banner.left.sample(3)
    @banners_right = Banner.right.sample(3)
    respond_to :js
  end
  
  private
  def not_found
    flash[:error] = 'page not found' and redirect_to root_path
  end
  
  def all_case
    @categories = Category.all
    @pages = Page.all
    @hot_items = Item.hots
    @favorite_items = Item.favorites
    @banners_left = Banner.left.sample(6)
    @banners_right = Banner.right.sample(6)
  end
  
  def unslug(slug)
    slug.split('-').join(' ') rescue ''
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def slug(obj)
    obj.name.split(' ').join('-') rescue ''
  end
end

app/views/admin/pages/_show.html.erb
<%= raw page.content %>

app/views/home/_banner.html.erb
<% banners.each do |b| %>
  <a href="<%= b.link_url %>" target='_blank'><img src="<%= b.image.url %>" alt="Banner" title="Banner" /></a>
<% end %>

app/views/home/_index.html.erb
<div class="content">
  <% if params[:controller] == 'home' && params[:action] == 'index' %>
	<div id="sliderFrame">
    <div id="slider">
      <a href='http://www.smpitnuruljannah.blogspot.com' target='_blank'><img src="/assets/nuruljannah.jpg" /></a>
      <a href='http://www.dijualchemical.blogspot.com' target='_blank'><img src="/assets/chemical.jpg"/></a>
      <a href='http://wwww.i-bossnetwork.com' target='_blank'><img src="/assets/iboss.jpg"/></a>
      <a href='http://airsehatcjdw.blogspot.com/' target='_blank'><img src="/assets/2.jpg"/></a>
      <a href='http://kampoengnagreg.com' target='_blank'><img src="/assets/3.jpg"/></a>
      <a href='#' target='_blank'><img src="/assets/6.jpg"/></a>
    </div>
  </div>
  <% end %>
	<div class="latest">
	<div class='p_right'>
	  <%= form_tag search_path, id: 'searches_item', method: 'get' do %>
	    <ul>
	      <li>
          <%= submit_tag 'btn-search', style: 'display:none;' %>
          <%= link_to 'Cari', '#', class: 'submit_search'%>
        </li>
	      <li>
	        <%= select_tag 'categories', options_for_select(@categories.map{|x| [x.name, x.id ]}.unshift('Kategori') ) %>
	      </li>
	      <li>
	        <div id="search">
            <input type="text" name="filter_name" placeholder='Cari Produk' />
          </div>
        </li>
      </ul>
    <% end %>
	</div>
  <p class="heading"><span>Produk Terbaru</span></p>
  <ul class="items">
    <% @items.each do |i| %>
      <li>
        <a class="image image-selector" href="#items_<%= i.id %>"><img src="<%= i.mini_url %>" width="120" height="120" /></a>
        <h3 class="name"><a href="<%= item_path(category: slug(i.category), item: slug(i)) %>" title="<%= i.name %>">
        <%= i.name.truncate(20) rescue '-' %></a></h3>
        <p class="price"><%= i.amount.to_i.display rescue '-' %> </p>

        <div class="clear"></div>     
      </li>
    <% end %>
  </ul>
  <% if @items.blank? %>
   <br/><br/><br/>
   <h3 style='text-align:center;'> Barang yang anda cari tidak ditemukan </h3>
  <% end %>
 <div class="clear"></div>  
 <%= paginate @items %>   
</div>

<% @items.each do |i| %>
  <div style="display:none"><div id="items_<%= i.id %>">
    <table width='500px'>
      <tr>
        <td colspan='2'>Order Sekarang >> SMS >> 087823400011<hr/></td>
      </tr>
      <tr>
        <td><img src="<%= i.mini_url %>" width="120" height="120" style='border: 1px solid; padding: 5px;' /></td>
        <td>
          Nama Barang: <%= i.name rescue '-' %> <br/>
          Harga Barang: <%= i.amount.to_i.display rescue '-' %><hr/> <br/>
          <span><%= link_to 'Lihat Detail', item_path(category: slug(i.category), item: slug(i)), class: 'btn-information' %></span>
        </td>
      </tr>
    </table>
  </div></div>
<% end %>

app/views/home/_sidebar.html.erb
<div id="column-right">
    <div class="box best">
  <div class="box-heading">Produk Terlaris</div>
  <div class="box-content">
    <ul class="best-sellers">
      <% @hot_items.each do |i| %>
        <li>
          <a class="image" href="<%= item_path(category: slug(i.category), item: slug(i)) %>"><img src="<%= i.thumb_url %>" /></a>
          <div class="bRight">
            <h4 class="name">
              <a href="<%= item_path(category: slug(i.category), item: slug(i)) %>"><%= i.name %></a>
            </h4>
            <p class="price"><%= i.amount.to_i.display %></p>
          </div>
          <div class="clear"></div>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="clear"></div>
</div>
<div id="banner_right">
  <%= render 'banner', banners: @banners_right %>
</div>
<%= google_adsense_include_tag client: 'ca-pub-7384515891659442', slot: '5712768604' %>
</div>

app/views/home/_sidebar_left.html.erb
<div id="column-left">
    <div class="box best">
  <div class="box-heading">Produk Unggulan</div>
  <div class="box-content">
    <ul class="best-sellers">
      <% @favorite_items.each do |i| %>
        <li>
          <a class="image" href="<%= item_path(category: slug(i.category), item: slug(i)) %>"><img src="<%= i.thumb_url %>" /></a>
          <div class="bRight">
            <h4 class="name">
              <a href="<%= item_path(category: slug(i.category), item: slug(i)) %>"><%= i.name %></a>
            </h4>
            <p class="price"><%= i.amount.to_i.display %></p>
          </div>
          <div class="clear"></div>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="clear"></div>
</div>
<div id="banner_left">
  <%= render 'banner', banners: @banners_left %>
</div>
<%= google_adsense_include_tag client: 'ca-pub-3932537892609136', slot: '7489506001' %>
</div>

app/views/home/banner.js.erb
$('#banner_right, #banner_left').show("slide")
$('#banner_right').html('<%= j(render 'banner', banners: @banners_right )%>')
$('#banner_left').html('<%= j(render 'banner', banners: @banners_left )%>')

app/views/home/category.html.erb
<%= render 'index' %>

app/views/home/index.html.erb
<%= render 'index' %>

app/views/home/item.html.erb
<style>
  div.image img{
    height: 100%
  }
  
  
.item_price {
    text-align: center;
    font-size: 26px;
}

</style>
<div class="content">
<div class="pWrap">
  <div class="product-info page-detail">
        <div class="pWrapper">
    <div class="left"><br/>
    <div class="image"><a href="<%= @item.images.first.image.url rescue '' %>" target="_blank" class="fancybox"><img src="<%= @item.large_url %>" /></a></div>
      <ul class="image-additional">
        <% @item.image_seconds.each do |m|%>
        <li><a href="<%= m.image.url %>" target="_blank" class="fancybox" rel="fancybox"><img src="<%= m.image.url(:thumb) %>" /></a></li>
        <% end %>
      </ul>
      
    <div class="clear"></div><br/>
    <div class='item_price'><%= @item.amount.to_i.display rescue 0 %></div>
    </div>
        
    <div class="right">      
    <div class="productDetails"><br/><br/>
    <h2><%= @item.name %></h2><br/>
       <div id='rating'>
         <% @item.rate.to_i.times do %>
           <%= image_tag('/assets/star-on.png') %>
         <% end %>
       </div><br/>
       <ul class="pInfo">
          <li>Stok Barang: <%= @item.available? %></li>
       </ul>
       
    <div class='item-description'>
     <%= simple_format @item.description %>
    </div>
    </div> 
    </div>
    </div></div></div>
    
    <div class="pWrap">
      <br/>
      <div class="product-info buy-product page-detail">
      <br/>
      <div>
       Beli Produk:
       
       <br/><br/>
       <%= form_tag process_buy_path do %>
         Nama Anda:<br/>
         <%= text_field_tag :name %><br/>
         <%= hidden_field_tag :item_id, @item.id %><br/>
         No Telepon:<br/>
         <%= text_field_tag :telepon %><br/>
         Alamat:<br/>
         <%= text_area_tag :alamat, nil, rows: 5 %><br/>
         <%= submit_tag 'kirim' %>
       <% end %>
       </div>
      </div>
    </div>
  <div class="clear"></div>
  </div>
  
  <%= render 'sidebar' %>
  <div class="clear"></div>
  </div>
</div>

app/views/home/page.html.erb
<style>
 .page-detail ul, .page-detail ol, .page-detail li, .page-detail p, .page-detail h1, .page-detail h2, .page-detail h3, .page-detail form, .page-detail fieldset, .page-detail a {
    border: 0 none !important;
    margin: auto !important;
}

.page-detail ol {
    list-style: decimal !important;
     padding: 0 25px !important;
}

.page-detail ol li{
    padding-left: 0px !important;
}

.page-detail ul {
    list-style-type: disc;
}
</style>
<div class="content">
<div class="pWrap">
  <div class="product-info page-detail ">
    <h3><%= @page.name.titleize rescue '-' %></h3>
    <br/>
    <p>
      <%= raw @page.content %>
    </p>
  </div>
  <div class="clear"></div>
</div>

app/views/home/search.html.erb
<%= render 'index' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Plasa98</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => false %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => false %>
  <%= csrf_meta_tags %>

  <script>
  <% if flash[:notice].present? || flash[:error].present? %>
    $(document).ready(function(){
      alert("<%= flash[:notice] || flash[:error] %>")
    })
  <% end %>
  </script>
</head>
<body class="home"><div id="container">
<div id="header">
      	              <h1 id="logo"><a href="/"><%= image_tag '/assets/logo.png', style: 'margin-top: 6px; width: 230px;'%> </a></h1>
        <div id='banner_telephone'>Layanan Konsumen | ✆ 081224567234 | Sms Center: 087823400011</div>
        <div id='banner_image'><%= image_tag '/assets/contact-woman.png', width: '140px' %></div>
       
<div class="topRight">
    <div id="search">
 
    </div>
    <div class="clear"></div>
</div>
<div class="clear"></div>
  <br/><br/>
        
  <div class="clear"></div> 
  </div> 
      <ul class="categories">
        <li><a href="/">Beranda</a></li>
        <% @pages.each do |p|%>
          <li class="level0"><a href="<%= page_path(slug(p))%>" class="level-top"><%= p.name %></a></li>
        <% end %>
        <!--
        <% @categories.each do |c| %>
        <li class="level0"><a href="<%= category_path(slug(c)) %>" class="level-top"><%= c.name.titleize %></a></li>
        <% end %>
          <!--
          <ul>
           <li><a href="#">Contoh 1</a></li>
           <li class="last"><a href="#">Contoh 2</a></li>
          </ul>
          -->
      </ul>
<div class="clear"></div>
<div class="clear"></div>  <br/><div id="wrapper">	
<%= render 'sidebar_left' %>
<%= yield %>
    
<div class="clear"></div>
</div>
<% if params[:controller] == 'home' && params[:action] != 'item' %>
  <%= render 'sidebar' %>
    <div class="clear"></div>
  </div>
  </div>
<% end %>
<div class="footer">
	<div class="footerWrapper">
          <div class="fooLeft">
            <p>
	<%= image_tag '/assets/logo-footer.png', style: 'width: 250px;'%>
	adalah Toko Online dengan konsep plasa menyediakan segala kebutuhan yang anda perlukan, lebih hemat dan efisien, apapun barang yang anda cari, semua ada di plasa98.com</p>
            
          </div>
       
         <div class="fooLinks">
         	  <p>Layanan Konsumen<br/><br/>
              ☎ 0812.24567.234 <br/>
              SMS: 0878.234.000.11<br/>
              ✉ info@plasa98.com<br/>
            </p>	
         </div>
         
         <div class="fooLinks">
         	 <p>Rekening Bank<br/><br/>
              Bank BRI<br/>
              0759-01-008750-53-9<br/>
              A/n : Jajang<br/>
              <%#= image_tag '/assets/bank.png', style: 'width: 60px;'%>
         </div>
         
         <div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/id_ID/sdk.js#xfbml=1&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

         <div class="fooLinks last facebook">
         	  <div class="fb-like-box" data-href="https://www.facebook.com/pages/Plasa98/1492884907628212?fref=ts" data-width="170" data-height="180" data-colorscheme="light" data-show-faces="true" data-header="false" data-stream="false" data-show-border="true"></div>
         </div>
         
         
         <div class="clear"></div>

   </div>
           
</div>
<div class="fooBottom">
          <p class="powered">@ company of Kreasi Niaga Mandiri 2014. Powered by <a href='#'>onlinenin.com</a></p>
</div>

<div id='leave_message'>
   Tinggalkan Pesan
</div>

<div id='leave_message_popup'>
   <%= form_tag contact_us_path do %>
    <table>
      <tr>
        <td colspan='2' style='background: gold; padding: 8px;'>✉ Tinggalkan Pesan <a href='javascript:void(0)' class='minimalize_popup'>X</a></td>
      </tr>
      <tr>
        <td><br/></td>
      </tr>
      <tr>
        <td>Nama:</td>
        <td><%= text_field_tag '[contact_us]name' %></td>
      </tr>
      <tr>
        <td>No handphone:</td>
        <td><%= text_field_tag '[contact_us]handphone', nil, class: 'for_phone' %></td>
      </tr>
      <tr>
        <td>Email:</td>
        <td><%= email_field_tag '[contact_us]email' %></td>
      </tr>
      <tr>
        <td>Pesan: </td>
        <td><%= text_area_tag '[contact_us]message' %></td>
      </tr>
      <tr>
        <td colspan='2'><%= submit_tag 'kirim pesan' %></td>
      </tr>
    </table>
  <% end %>
</div>
</body></html>